image: python:3.4

before_script:
  - pip install virtualenv
  - virtualenv --system-site-packages venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - cp landmatrix/settings.py.dist landmatrix/settings.py

services:
  - postgis:latest

variables:
  POSTGRES_DB: landmatrix
  POSTGRES_USER: landmatrix
  POSTGRES_PASSWORD: ""

test:
  script:
    - python manage.py test
