image: python:3.4

before_script:
  - pip install virtualenv
  - virtualenv --system-site-packages venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - cp landmatrix/settings.py.dist landmatrix/settings.py
  - python manage.py migrate

services:
  - mdillon/postgis:latest
  - elasticsearch:latest
  - redis:latest

variables:
  POSTGRES_DB: landmatrix
  POSTGRES_USER: landmatrix
  POSTGRES_PASSWORD: ""

test:
  script:
    - venv/bin/python manage.py test
