image: python:3.4

before_script:
  - pip install virtualenv
  - virtualenv --system-site-packages venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  script:
    - python manage.py test
